trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
- job: 'build_ubuntu'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
    displayName: 'Install dependencies'
  - script: |
      python setup.py freeze
    displayName: 'Freeze application'
  - task: Bash@3
    inputs:
      filePath: 'scripts/build_deb.sh'
      arguments: 'deb'
    displayName: 'Build .deb file'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/build'
      Contents: 'idfplus-0.1.0b8.deb'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'idfplus-0.1.0b8.deb'

- job: 'build_windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 2
  steps:
  - script: echo hello from Windows
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
    displayName: 'Install dependencies'
  - script: |
      python setup.py freeze
    displayName: 'Freeze application'
  - script: |
      python setup.py bdist_msi
    displayName: 'Build msi'
  - task: PublishTestResults@2
    inputs:
      testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
    condition: succeededOrFailed()
  - task: CopyFiles@2
    displayName: Copy build artifact
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\dist'
      Contents: 'idfplus-v0.2.0.msi'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      OverWrite: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'idfplus-v0.2.0.msi'
    displayName: Publish artifacts
