name: IDFPlus Build Workflow Test

on:
  push:
    branches:
      - build-workflow-testing

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install global dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install ubuntu-specific dependencies
        if: startswith(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y debhelper

      - name: Freeze the app
        run: |
          python setup.py freeze

      - name: Package the app
        run: |
          python setup.py bdist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts
